# DESCRIPTION
# playbook that will add nodes to F5 BigIP
#
# REQUIREMENTS
#
# STEPS
# update the appropriate var files with your own settings
#
# ansible-playbook -v add-node.yml
#
#


---

###################################################################################

- hosts: localhost
  gather_facts: no
  connection: local

  #Variable file included
  vars_files:
    - var-add-node-file.yml

  roles:
    - add-node