---

  # Add the POOL on F5 BIG-IP
  - name: Create a POOL
    bigip_pool:
      provider: "{{ provider }}"
      state: "{{ item.pool_state }}"
      partition: "{{ item.pool_partition }}"
      name: "{{ item.pool_name }}"
      description: "{{ item.pool_description }}"
      lb_method: "{{ item.pool_lb_method }}"
      monitor_type: "{{ item.pool_monitor_type }}"
      monitors: "{{ item.pool_monitors }}"
    with_items: "{{ pool_information }}"
    delegate_to: localhost
